write(getMat,*)"#!/bin/bash"
write(getMat,*)
write(getMat,*)"cat > plot-distrib-tmp <<EOF"
write(getMat,*)
write(getMat,*)"width = 0.002"
write(getMat,*)"set boxwidth width absolute"
write(getMat,*)"set style fill solid 1.0"
write(getMat,*)"bin_width = width;"
write(getMat,*)"bin_number(x) = floor(x/bin_width)"
write(getMat,*)"rounded(x) = bin_width * ( bin_number(x) )"
write(getMat,*)"set table 'test1.dat'"
write(getMat,*)"plot 'Etransitions-he_ei.dat' using (rounded(\$4)):(1) smooth frequency "
write(getMat,*)"unset table"
write(getMat,*)"set table 'test2.dat'"
write(getMat,*)"plot 'Etransitions-he_ei.dat' using (rounded(\$5)):(1) smooth frequency "
write(getMat,*)"unset table"
write(getMat,*)"set table 'test3.dat'"
write(getMat,*)"plot 'Etransitions-he_ei.dat' using (rounded(\$6)):(1) smooth frequency "
write(getMat,*)"unset table"
write(getMat,*)"set table 'test4.dat'"
write(getMat,*)"plot 'Etransitions-he_ei.dat' using (rounded(\$7)):(1) smooth frequency "
write(getMat,*)"unset table"
write(getMat,*)"set table 'test5.dat'"
write(getMat,*)"plot 'Etransitions-he_ei.dat' using (rounded(\$8)):(1) smooth frequency "
write(getMat,*)"unset table"
write(getMat,*)"set table 'test6.dat'"
write(getMat,*)"plot 'Etransitions-he_ei.dat' using (rounded(\$9)):(1) smooth frequency "
write(getMat,*)"unset table"
write(getMat,*)"set table 'test7.dat'"
write(getMat,*)"plot 'Etransitions-he_ei.dat' using (rounded(\$10)):(1) smooth frequency"
write(getMat,*)"unset table"
write(getMat,*)"set table 'test8.dat'"
write(getMat,*)"plot 'Etransitions-he_ei.dat' using (rounded(\$11)):(1) smooth frequency "
write(getMat,*)"unset table"
write(getMat,*)
write(getMat,*)"set table 'test-1-2.dat'"
write(getMat,*)"plot 'Etransitions-he_ei.dat' using (rounded(\$5-\$4)):(1) smooth frequency"
write(getMat,*)"unset table"
write(getMat,*)"set table 'test-1-3.dat'"
write(getMat,*)"plot 'Etransitions-he_ei.dat' using (rounded(\$6-\$4)):(1) smooth frequency"
write(getMat,*)"unset table"
write(getMat,*)"set table 'test-1-4.dat'"
write(getMat,*)"plot 'Etransitions-he_ei.dat' using (rounded(\$7-\$4)):(1) smooth frequency"
write(getMat,*)"unset table"
write(getMat,*)"set table 'test-1-5.dat'"
write(getMat,*)"plot 'Etransitions-he_ei.dat' using (rounded(\$8-\$4)):(1) smooth frequency"
write(getMat,*)"unset table"
write(getMat,*)"set table 'test-1-6.dat'"
write(getMat,*)"plot 'Etransitions-he_ei.dat' using (rounded(\$9-\$4)):(1) smooth frequency"
write(getMat,*)"unset table"
write(getMat,*)"set table 'test-1-7.dat'"
write(getMat,*)"plot 'Etransitions-he_ei.dat' using (rounded(\$10-\$4)):(1) smooth frequency"
write(getMat,*)"unset table"
write(getMat,*)"set table 'test-1-8.dat'"
write(getMat,*)"plot 'Etransitions-he_ei.dat' using (rounded(\$11-\$4)):(1) smooth frequency"
write(getMat,*)"unset table"
write(getMat,*)
write(getMat,*)"set table 'test-2-3.dat'"
write(getMat,*)"plot 'Etransitions-he_ei.dat' using (rounded(\$6-\$5)):(1) smooth frequency"
write(getMat,*)"unset table"
write(getMat,*)"set table 'test-2-4.dat'"
write(getMat,*)"plot 'Etransitions-he_ei.dat' using (rounded(\$7-\$5)):(1) smooth frequency"
write(getMat,*)"unset table"
write(getMat,*)"set table 'test-2-5.dat'"
write(getMat,*)"plot 'Etransitions-he_ei.dat' using (rounded(\$8-\$5)):(1) smooth frequency"
write(getMat,*)"unset table"
write(getMat,*)"set table 'test-2-6.dat'"
write(getMat,*)"plot 'Etransitions-he_ei.dat' using (rounded(\$9-\$5)):(1) smooth frequency"
write(getMat,*)"unset table"
write(getMat,*)"set table 'test-2-7.dat'"
write(getMat,*)"plot 'Etransitions-he_ei.dat' using (rounded(\$10-\$5)):(1) smooth frequency"
write(getMat,*)"unset table"
write(getMat,*)"set table 'test-2-8.dat'"
write(getMat,*)"plot 'Etransitions-he_ei.dat' using (rounded(\$11-\$5)):(1) smooth frequency"
write(getMat,*)"unset table"
write(getMat,*)
write(getMat,*)"set table 'test-3-4.dat'"
write(getMat,*)"plot 'Etransitions-he_ei.dat' using (rounded(\$7-\$6)):(1) smooth frequency"
write(getMat,*)"unset table"
write(getMat,*)"set table 'test-3-5.dat'"
write(getMat,*)"plot 'Etransitions-he_ei.dat' using (rounded(\$8-\$6)):(1) smooth frequency"
write(getMat,*)"unset table"
write(getMat,*)"set table 'test-3-6.dat'"
write(getMat,*)"plot 'Etransitions-he_ei.dat' using (rounded(\$9-\$6)):(1) smooth frequency"
write(getMat,*)"unset table"
write(getMat,*)"set table 'test-3-7.dat'"
write(getMat,*)"plot 'Etransitions-he_ei.dat' using (rounded(\$10-\$6)):(1) smooth frequency"
write(getMat,*)"unset table"
write(getMat,*)"set table 'test-3-8.dat'"
write(getMat,*)"plot 'Etransitions-he_ei.dat' using (rounded(\$11-\$6)):(1) smooth frequency"
write(getMat,*)"unset table"
write(getMat,*)
write(getMat,*)"set table 'test-4-5.dat'"
write(getMat,*)"plot 'Etransitions-he_ei.dat' using (rounded(\$8-\$7)):(1) smooth frequency"
write(getMat,*)"unset table"
write(getMat,*)"set table 'test-4-6.dat'"
write(getMat,*)"plot 'Etransitions-he_ei.dat' using (rounded(\$9-\$7)):(1) smooth frequency"
write(getMat,*)"unset table"
write(getMat,*)"set table 'test-4-7.dat'"
write(getMat,*)"plot 'Etransitions-he_ei.dat' using (rounded(\$10-\$7)):(1) smooth frequency"
write(getMat,*)"unset table"
write(getMat,*)"set table 'test-4-8.dat'"
write(getMat,*)"plot 'Etransitions-he_ei.dat' using (rounded(\$11-\$7)):(1) smooth frequency"
write(getMat,*)"unset table"
write(getMat,*)
write(getMat,*)"set table 'test-5-6.dat'"
write(getMat,*)"plot 'Etransitions-he_ei.dat' using (rounded(\$9-\$8)):(1) smooth frequency"
write(getMat,*)"unset table"
write(getMat,*)"set table 'test-5-7.dat'"
write(getMat,*)"plot 'Etransitions-he_ei.dat' using (rounded(\$10-\$8)):(1) smooth frequency"
write(getMat,*)"unset table"
write(getMat,*)"set table 'test-5-8.dat'"
write(getMat,*)"plot 'Etransitions-he_ei.dat' using (rounded(\$11-\$8)):(1) smooth frequency"
write(getMat,*)"unset table"
write(getMat,*)
write(getMat,*)"set table 'test-6-7.dat'"
write(getMat,*)"plot 'Etransitions-he_ei.dat' using (rounded(\$10-\$9)):(1) smooth frequency"
write(getMat,*)"unset table"
write(getMat,*)"set table 'test-6-8.dat'"
write(getMat,*)"plot 'Etransitions-he_ei.dat' using (rounded(\$11-\$9)):(1) smooth frequency"
write(getMat,*)"unset table"
write(getMat,*)
write(getMat,*)"set table 'test-7-8.dat'"
write(getMat,*)"plot 'Etransitions-he_ei.dat' using (rounded(\$11-\$10)):(1) smooth frequency"
write(getMat,*)"unset table"
write(getMat,*)
write(getMat,*)"a2=2.5" 
write(getMat,*)"b2=2.5"
write(getMat,*)"c2=2.5"
write(getMat,*)"d2=2.5"
write(getMat,*)"e2=2.5"
write(getMat,*)"f2=2.5"
write(getMat,*)"g2=2.5"
write(getMat,*)"h2=2.5" 
write(getMat,*)
write(getMat,*)"f1(x) = (a1/(a3*(2*pi)**0.5))*exp(-(x-a2)**2/(2*(a3)**2))"
write(getMat,*)"f2(x) = (b1/(b3*(2*pi)**0.5))*exp(-(x-b2)**2/(2*(b3)**2))"
write(getMat,*)"f3(x) = (c1/(c3*(2*pi)**0.5))*exp(-(x-c2)**2/(2*(c3)**2))"
write(getMat,*)"f4(x) = (d1/(d3*(2*pi)**0.5))*exp(-(x-d2)**2/(2*(d3)**2))"
write(getMat,*)"f5(x) = (e1/(e3*(2*pi)**0.5))*exp(-(x-e2)**2/(2*(e3)**2))"
write(getMat,*)"f6(x) = (f1/(f3*(2*pi)**0.5))*exp(-(x-f2)**2/(2*(f3)**2))"
write(getMat,*)"f7(x) = (g1/(g3*(2*pi)**0.5))*exp(-(x-g2)**2/(2*(g3)**2))"
write(getMat,*)"f8(x) = (h1/(h3*(2*pi)**0.5))*exp(-(x-h2)**2/(2*(h3)**2))" 
write(getMat,*)
write(getMat,*)"f_1_2(x)=&
(x_1_2/((a3**2+b3**2-2*rho_1_2*a3*b3)**0.5*(2*pi)**0.5))*exp(-(x-(b2-a2))**2/(2*(a3**2+b3**2+2*rho_1_2*a3*b3)))"
write(getMat,*)"f_1_3(x)=&
(x_1_3/((a3**2+c3**2+2*rho_1_3*a3*c3)**0.5*(2*pi)**0.5))*exp(-(x-(c2-a2))**2/(2*(a3**2+c3**2+2*rho_1_3*a3*c3)))"
write(getMat,*)"f_1_4(x)=&
(x_1_4/((a3**2+d3**2+2*rho_1_4*a3*d3)**0.5*(2*pi)**0.5))*exp(-(x-(d2-a2))**2/(2*(a3**2+d3**2+2*rho_1_4*a3*d3)))"
write(getMat,*)"f_1_5(x)=&
(x_1_5/((a3**2+e3**2+2*rho_1_5*a3*e3)**0.5*(2*pi)**0.5))*exp(-(x-(e2-a2))**2/(2*(a3**2+e3**2+2*rho_1_5*a3*e3)))"
write(getMat,*)"f_1_6(x)=&
(x_1_6/((a3**2+f3**2+2*rho_1_6*a3*f3)**0.5*(2*pi)**0.5))*exp(-(x-(f2-a2))**2/(2*(a3**2+f3**2+2*rho_1_6*a3*f3)))"
write(getMat,*)"f_1_7(x)=&
(x_1_7/((a3**2+g3**2+2*rho_1_7*a3*g3)**0.5*(2*pi)**0.5))*exp(-(x-(g2-a2))**2/(2*(a3**2+g3**2+2*rho_1_7*a3*g3)))"
write(getMat,*)"f_1_8(x)=&
(x_1_8/((a3**2+h3**2+2*rho_1_8*a3*h3)**0.5*(2*pi)**0.5))*exp(-(x-(h2-a2))**2/(2*(a3**2+h3**2+2*rho_1_8*a3*h3)))"
write(getMat,*)
write(getMat,*)"f_2_3(x)=&
(x_2_3/((b3**2+c3**2+2*rho_2_3*b3*c3)**0.5*(2*pi)**0.5))*exp(-(x-(c2-b2))**2/(2*(b3**2+c3**2+2*rho_2_3*b3*c3)))"
write(getMat,*)"f_2_4(x)=&
(x_2_4/((b3**2+d3**2+2*rho_2_4*b3*d3)**0.5*(2*pi)**0.5))*exp(-(x-(d2-b2))**2/(2*(b3**2+d3**2+2*rho_2_4*b3*d3)))"
write(getMat,*)"f_2_5(x)=&
(x_2_5/((b3**2+e3**2+2*rho_2_5*b3*e3)**0.5*(2*pi)**0.5))*exp(-(x-(e2-b2))**2/(2*(b3**2+e3**2+2*rho_2_5*b3*e3)))"
write(getMat,*)"f_2_6(x)=&
(x_2_6/((b3**2+f3**2+2*rho_2_6*b3*f3)**0.5*(2*pi)**0.5))*exp(-(x-(f2-b2))**2/(2*(b3**2+f3**2+2*rho_2_6*b3*f3)))"
write(getMat,*)"f_2_7(x)=&
(x_2_7/((b3**2+g3**2+2*rho_2_7*b3*g3)**0.5*(2*pi)**0.5))*exp(-(x-(g2-b2))**2/(2*(b3**2+g3**2+2*rho_2_7*b3*g3)))"
write(getMat,*)"f_2_8(x)=&
(x_2_8/((b3**2+h3**2+2*rho_2_8*b3*h3)**0.5*(2*pi)**0.5))*exp(-(x-(h2-b2))**2/(2*(b3**2+h3**2+2*rho_2_8*b3*h3)))"
write(getMat,*)
write(getMat,*)"f_3_4(x)=&
(x_3_4/((c3**2+d3**2+2*rho_3_4*c3*d3)**0.5*(2*pi)**0.5))*exp(-(x-(d2-c2))**2/(2*(c3**2+d3**2+2*rho_3_4*c3*d3)))"
write(getMat,*)"f_3_5(x)=&
(x_3_5/((c3**2+e3**2+2*rho_3_5*c3*e3)**0.5*(2*pi)**0.5))*exp(-(x-(e2-c2))**2/(2*(c3**2+e3**2+2*rho_3_5*c3*e3)))"
write(getMat,*)"f_3_6(x)=&
(x_3_6/((c3**2+f3**2+2*rho_3_6*c3*f3)**0.5*(2*pi)**0.5))*exp(-(x-(f2-c2))**2/(2*(c3**2+f3**2+2*rho_3_6*c3*f3)))"
write(getMat,*)"f_3_7(x)=&
(x_3_7/((c3**2+g3**2+2*rho_3_7*c3*g3)**0.5*(2*pi)**0.5))*exp(-(x-(g2-c2))**2/(2*(c3**2+g3**2+2*rho_3_7*c3*g3)))"
write(getMat,*)"f_3_8(x)=&
(x_3_8/((c3**2+h3**2+2*rho_3_8*c3*h3)**0.5*(2*pi)**0.5))*exp(-(x-(h2-c2))**2/(2*(c3**2+h3**2+2*rho_3_8*c3*h3)))"
write(getMat,*)
write(getMat,*)"f_4_5(x)=&
(x_4_5/((d3**2+e3**2+2*rho_4_5*d3*e3)**0.5*(2*pi)**0.5))*exp(-(x-(e2-d2))**2/(2*(d3**2+e3**2+2*rho_4_5*d3*e3)))"
write(getMat,*)"f_4_6(x)=&
(x_4_6/((d3**2+f3**2+2*rho_4_6*d3*f3)**0.5*(2*pi)**0.5))*exp(-(x-(f2-d2))**2/(2*(d3**2+f3**2+2*rho_4_6*d3*f3)))"
write(getMat,*)"f_4_7(x)=&
(x_4_7/((d3**2+g3**2+2*rho_4_7*d3*g3)**0.5*(2*pi)**0.5))*exp(-(x-(g2-d2))**2/(2*(d3**2+g3**2+2*rho_4_7*d3*g3)))"
write(getMat,*)"f_4_8(x)=&
(x_4_8/((d3**2+h3**2+2*rho_4_8*d3*h3)**0.5*(2*pi)**0.5))*exp(-(x-(h2-d2))**2/(2*(d3**2+h3**2+2*rho_4_8*d3*h3)))"
write(getMat,*)
write(getMat,*)"f_5_6(x)=&
(x_5_6/((e3**2+f3**2+2*rho_5_6*e3*f3)**0.5*(2*pi)**0.5))*exp(-(x-(f2-e2))**2/(2*(e3**2+f3**2+2*rho_5_6*e3*f3)))"
write(getMat,*)"f_5_7(x)=&
(x_5_7/((e3**2+g3**2+2*rho_5_7*e3*g3)**0.5*(2*pi)**0.5))*exp(-(x-(g2-e2))**2/(2*(e3**2+g3**2+2*rho_5_7*e3*g3)))"
write(getMat,*)"f_5_8(x)=&
(x_5_8/((e3**2+h3**2+2*rho_5_8*e3*h3)**0.5*(2*pi)**0.5))*exp(-(x-(h2-e2))**2/(2*(e3**2+h3**2+2*rho_5_8*e3*h3)))"
write(getMat,*)
write(getMat,*)"f_6_7(x)=&
(x_6_7/((f3**2+g3**2+2*rho_6_7*f3*g3)**0.5*(2*pi)**0.5))*exp(-(x-(g2-f2))**2/(2*(f3**2+g3**2+2*rho_6_7*f3*g3)))"
write(getMat,*)"f_6_8(x)=&
(x_6_8/((f3**2+h3**2+2*rho_6_8*f3*h3)**0.5*(2*pi)**0.5))*exp(-(x-(h2-f2))**2/(2*(f3**2+h3**2+2*rho_6_8*f3*h3)))"
write(getMat,*)
write(getMat,*)"f_7_8(x)=&
(x_7_8/((g3**2+h3**2+2*rho_7_8*g3*h3)**0.5*(2*pi)**0.5))*exp(-(x-(h2-g2))**2/(2*(g3**2+h3**2+2*rho_7_8*g3*h3)))" 
write(getMat,*)
write(getMat,*)"fit f1(x) 'test1.dat' via a1,a2,a3"
write(getMat,*)"save fit 'fit1.dat'"
write(getMat,*)"fit f2(x) 'test2.dat' via b1,b2,b3"
write(getMat,*)"save fit 'fit2.dat'"
write(getMat,*)"fit f3(x) 'test3.dat' via c1,c2,c3"
write(getMat,*)"save fit 'fit3.dat'"
write(getMat,*)"fit f4(x) 'test4.dat' via d1,d2,d3"
write(getMat,*)"save fit 'fit4.dat'"
write(getMat,*)"fit f5(x) 'test5.dat' via e1,e2,e3"
write(getMat,*)"save fit 'fit5.dat'"
write(getMat,*)"fit f6(x) 'test6.dat' via f1,f2,f3"
write(getMat,*)"save fit 'fit6.dat'"
write(getMat,*)"fit f7(x) 'test7.dat' via g1,g2,g3"
write(getMat,*)"save fit 'fit7.dat'"
write(getMat,*)"fit f8(x) 'test8.dat' via h1,h2,h3" 
write(getMat,*)"save fit 'fit8.dat'"
write(getMat,*)
write(getMat,*)"fit f_1_2(x) 'test-1-2.dat' via x_1_2,rho_1_2" 
write(getMat,*)"save fit 'fit_1_2.dat'"
write(getMat,*)"fit f_1_3(x) 'test-1-3.dat' via x_1_3,rho_1_3"
write(getMat,*)"save fit 'fit_1_3.dat'"
write(getMat,*)"fit f_1_4(x) 'test-1-4.dat' via x_1_4,rho_1_4"
write(getMat,*)"save fit 'fit_1_4.dat'"
write(getMat,*)"fit f_1_5(x) 'test-1-5.dat' via x_1_5,rho_1_5"
write(getMat,*)"save fit 'fit_1_5.dat'"
write(getMat,*)"fit f_1_6(x) 'test-1-6.dat' via x_1_6,rho_1_6"
write(getMat,*)"save fit 'fit_1_6.dat'"
write(getMat,*)"fit f_1_7(x) 'test-1-7.dat' via x_1_7,rho_1_7"
write(getMat,*)"save fit 'fit_1_7.dat'"
write(getMat,*)"fit f_1_8(x) 'test-1-8.dat' via x_1_8,rho_1_8"
write(getMat,*)"save fit 'fit_1_8.dat'"
write(getMat,*)
write(getMat,*)"fit f_2_3(x) 'test-2-3.dat' via x_2_3,rho_2_3"
write(getMat,*)"save fit 'fit_2_3.dat'"
write(getMat,*)"fit f_2_4(x) 'test-2-4.dat' via x_2_4,rho_2_4"
write(getMat,*)"save fit 'fit_2_4.dat'"
write(getMat,*)"fit f_2_5(x) 'test-2-5.dat' via x_2_5,rho_2_5"
write(getMat,*)"save fit 'fit_2_5.dat'"
write(getMat,*)"fit f_2_6(x) 'test-2-6.dat' via x_2_6,rho_2_6"
write(getMat,*)"save fit 'fit_2_6.dat'"
write(getMat,*)"fit f_2_7(x) 'test-2-7.dat' via x_2_7,rho_2_7"
write(getMat,*)"save fit 'fit_2_7.dat'"
write(getMat,*)"fit f_2_8(x) 'test-2-8.dat' via x_2_8,rho_2_8"
write(getMat,*)"save fit 'fit_2_8.dat'"
write(getMat,*)
write(getMat,*)"fit f_3_4(x) 'test-3-4.dat' via x_3_4,rho_3_4"
write(getMat,*)"save fit 'fit_3_4.dat'"
write(getMat,*)"fit f_3_5(x) 'test-3-5.dat' via x_3_5,rho_3_5"
write(getMat,*)"save fit 'fit_3_5.dat'"
write(getMat,*)"fit f_3_6(x) 'test-3-6.dat' via x_3_6,rho_3_6"
write(getMat,*)"save fit 'fit_3_6.dat'"
write(getMat,*)"fit f_3_7(x) 'test-3-7.dat' via x_3_7,rho_3_7"
write(getMat,*)"save fit 'fit_3_7.dat'"
write(getMat,*)"fit f_3_8(x) 'test-3-8.dat' via x_3_8,rho_3_8"
write(getMat,*)"save fit 'fit_3_8.dat'"
write(getMat,*)
write(getMat,*)"fit f_4_5(x) 'test-4-5.dat' via x_4_5,rho_4_5"
write(getMat,*)"save fit 'fit_4_5.dat'"
write(getMat,*)"fit f_4_6(x) 'test-4-6.dat' via x_4_6,rho_4_6"
write(getMat,*)"save fit 'fit_4_6.dat'"
write(getMat,*)"fit f_4_7(x) 'test-4-7.dat' via x_4_7,rho_4_7"
write(getMat,*)"save fit 'fit_4_7.dat'"
write(getMat,*)"fit f_4_8(x) 'test-4-8.dat' via x_4_8,rho_4_8"
write(getMat,*)"save fit 'fit_4_8.dat'"
write(getMat,*)
write(getMat,*)"fit f_5_6(x) 'test-5-6.dat' via x_5_6,rho_5_6"
write(getMat,*)"save fit 'fit_5_6.dat'"
write(getMat,*)"fit f_5_7(x) 'test-5-7.dat' via x_5_7,rho_5_7"
write(getMat,*)"save fit 'fit_5_7.dat'"
write(getMat,*)"fit f_5_8(x) 'test-5-8.dat' via x_5_8,rho_5_8"
write(getMat,*)"save fit 'fit_5_8.dat'"
write(getMat,*)
write(getMat,*)"fit f_6_7(x) 'test-6-7.dat' via x_6_7,rho_6_7" 
write(getMat,*)"save fit 'fit_6_7.dat'"
write(getMat,*)"fit f_6_8(x) 'test-6-8.dat' via x_6_8,rho_6_8"
write(getMat,*)"save fit 'fit_6_8.dat'"
write(getMat,*)
write(getMat,*)"fit f_7_8(x) 'test-7-8.dat' via x_7_8,rho_7_8"
write(getMat,*)"save fit 'fit_7_8.dat'"
write(getMat,*)
write(getMat,*)"EOF"
write(getMat,*)
write(getMat,*)"gnuplot plot-distrib-tmp 2> tmp"
write(getMat,*)
write(getMat,*)"rm tmp2 tmp3"
write(getMat,*)
write(getMat,*)"grep 'a3              =' fit1.dat | awk '{print $3}' >> tmp2" 
write(getMat,*)"grep 'b3              =' fit2.dat | awk '{print $3}' >> tmp2"
write(getMat,*)"grep 'c3              =' fit3.dat | awk '{print $3}' >> tmp2"
write(getMat,*)"grep 'd3              =' fit4.dat | awk '{print $3}' >> tmp2"
write(getMat,*)"grep 'e3              =' fit5.dat | awk '{print $3}' >> tmp2"
write(getMat,*)"grep 'f3              =' fit6.dat | awk '{print $3}' >> tmp2"
write(getMat,*)"grep 'g3              =' fit7.dat | awk '{print $3}' >> tmp2"
write(getMat,*)"grep 'h3              =' fit8.dat | awk '{print $3}' >> tmp2"
write(getMat,*)
write(getMat,*)"grep 'rho_...         =' fit_1_2.dat | awk '{print $3, '1-2', '1 ' }' >> tmp3 " 
write(getMat,*)"grep 'rho_...         =' fit_1_3.dat | awk '{print $3, '1-3', '2 ' }' >> tmp3 "
write(getMat,*)"grep 'rho_...         =' fit_1_4.dat | awk '{print $3, '1-4', '3 ' }' >> tmp3 "
write(getMat,*)"grep 'rho_...         =' fit_1_5.dat | awk '{print $3, '1-5', '4 ' }' >> tmp3 "
write(getMat,*)"grep 'rho_...         =' fit_1_6.dat | awk '{print $3, '1-6', '5 ' }' >> tmp3 "
write(getMat,*)"grep 'rho_...         =' fit_1_7.dat | awk '{print $3, '1-7', '6 ' }' >> tmp3 "
write(getMat,*)"grep 'rho_...         =' fit_1_8.dat | awk '{print $3, '1-8', '7 ' }' >> tmp3 "
write(getMat,*)"grep 'rho_...         =' fit_2_3.dat | awk '{print $3, '2-3', '8 ' }' >> tmp3 "
write(getMat,*)"grep 'rho_...         =' fit_2_4.dat | awk '{print $3, '2-4', '9 ' }' >> tmp3 "
write(getMat,*)"grep 'rho_...         =' fit_2_5.dat | awk '{print $3, '2-5', '10' }' >> tmp3"
write(getMat,*)"grep 'rho_...         =' fit_2_6.dat | awk '{print $3, '2-6', '11' }' >> tmp3"
write(getMat,*)"grep 'rho_...         =' fit_2_7.dat | awk '{print $3, '2-7', '12' }' >> tmp3"
write(getMat,*)"grep 'rho_...         =' fit_2_8.dat | awk '{print $3, '2-8', '13' }' >> tmp3"
write(getMat,*)"grep 'rho_...         =' fit_3_4.dat | awk '{print $3, '3-4', '14' }' >> tmp3"
write(getMat,*)"grep 'rho_...         =' fit_3_5.dat | awk '{print $3, '3-5', '15' }' >> tmp3"
write(getMat,*)"grep 'rho_...         =' fit_3_6.dat | awk '{print $3, '3-6', '16' }' >> tmp3"
write(getMat,*)"grep 'rho_...         =' fit_3_7.dat | awk '{print $3, '3-7', '17' }' >> tmp3"
write(getMat,*)"grep 'rho_...         =' fit_3_8.dat | awk '{print $3, '3-8', '18' }' >> tmp3"
write(getMat,*)"grep 'rho_...         =' fit_4_5.dat | awk '{print $3, '4-5', '19' }' >> tmp3"
write(getMat,*)"grep 'rho_...         =' fit_4_6.dat | awk '{print $3, '4-6', '20' }' >> tmp3"
write(getMat,*)"grep 'rho_...         =' fit_4_7.dat | awk '{print $3, '4-7', '21' }' >> tmp3"
write(getMat,*)"grep 'rho_...         =' fit_4_8.dat | awk '{print $3, '4-8', '22' }' >> tmp3"
write(getMat,*)"grep 'rho_...         =' fit_5_6.dat | awk '{print $3, '5-6', '23' }' >> tmp3"
write(getMat,*)"grep 'rho_...         =' fit_5_7.dat | awk '{print $3, '5-7', '24' }' >> tmp3"
write(getMat,*)"grep 'rho_...         =' fit_5_8.dat | awk '{print $3, '5-8', '25' }' >> tmp3"
write(getMat,*)"grep 'rho_...         =' fit_6_7.dat | awk '{print $3, '6-7', '26' }' >> tmp3"
write(getMat,*)"grep 'rho_...         =' fit_6_8.dat | awk '{print $3, '6-8', '27' }' >> tmp3"
write(getMat,*)"grep 'rho_...         =' fit_7_8.dat | awk '{print $3, '7-8', '28' }' >> tmp3" 
